IB/mlx5: Replace non-supported function clear_thread_tidr
PPC system compilation failed with the below erroe
        error: implicit declaration of function 'clear_thread_tidr'; did you
        mean 'set_thread_tidr'? [-Werror=implicit-function-declaration]

Fixing it by replace the function according to the Backports in 4.5.

issue:1627970
Fixes: ff9de3c3d437 ("IB/mlx5: as_notify Add as_notify control via experimental verbs")
Change-Id: Ib4eeeba180d7bcd5471710a5022f43a0ff5451a5
Signed-off-by: Talat Batheesh <talatb@mellanox.com>